config/routes.rb
Gistclone::Application.routes.draw do
	root to: 'gists#index'

	resource :session, only: [:new, :create, :destroy]
	resources :users
	resources :favorites, only: [:index]
	resources :gists do
		resource :favorite, only: [:create, :destroy]
	end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	attr_accessible :user_id, :gist_id

	belongs_to :user
	belongs_to :gist

	validates :user_id, :gist_id, presence: true
	validates_uniqueness_of :user_id, scope: :gist_id
end

app/models/gist.rb
class Gist < ActiveRecord::Base
	attr_accessible :title, :user_id, :gist_files_attributes

	belongs_to :user
	has_many :gist_files, dependent: :destroy
	accepts_nested_attributes_for :gist_files
	has_many :favorites

	validates :title, presence: true
end

app/models/gist_file.rb
class GistFile < ActiveRecord::Base
	attr_accessible :body, :gist_id

	belongs_to :gist
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save :create_remember_token

	attr_accessible :name

	has_many :gists
	has_many :favorites
	has_many :favorite_gists, :through => :favorites, :source => :gist

	validates :name, presence: true, uniqueness: true

	private

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include ApplicationHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	respond_to :json

	def create
		@favorite = Favorite.new(user_id: current_user.id,
			 											 gist_id: params[:gist_id])
		if @favorite.save
			render json: @favorite
		else
			render json: @favorite.errors.full_messages, status: 422
		end
	end

	def index
		@favorites = current_user.favorites
		render json: @favorites
	end

	def destroy
		@favorite = current_user.favorites.find_by_gist_id(params[:gist_id])
		@favorite.destroy
		render json: @favorite
	end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
	respond_to :json, :only => [:index]
	respond_to :html, :only => [:index]

	def index
		if current_user
			@gists = current_user.gists
			respond_to do |format|
				format.html { render :index }
				format.json { render @gists }
			end
		else
			redirect_to new_session_url
		end
	end

	def create
		#debugger
		params[:gist][:gist_files_attributes] ||= []
		@gist = current_user.gists.new(params[:gist])
		@gist.gist_files ||= []
		if @gist.save
			render json: @gist
		else
			render json: @gist.errors.full_messages, status: 422
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by_name(params[:user][:name])
		if user
			sign_in user
			redirect_to root_url
		else
			flash.now[:error] = "Invalid user name"
			render :new
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			redirect_to root_url
		else
			render :new
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SessionHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def current_user=(user)
    @current_user
  end

	def current_user
    @user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end
end

app/views/gists/index.html.erb
<%= content_tag "div", "", id: "content", data: {favorites: Favorite.all} %>

<script type="text/javascript">
  $(function() {
    var gistsData = <%= @gists.to_json.html_safe %>;

    window.G.initialize(
      $("#content"),
      gistsData
    );
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gistclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <pre><%= params %></pre>

  <header>
    <ul>
      <% if current_user %>
        <li><%= link_to "sign out", session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "sign up", new_user_path %></li>
        <li><%= link_to "sign in", new_session_path %></li>
      <% end %>
    </ul>
  </header>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'submit' %>
<% end %>